---
language: objective-c

before_script:
  - sudo easy_install cpp-coveralls

script: 
 - xctool -project DTMarkdownParser.xcodeproj -scheme "DTMarkdownParser (Mac)" test -configuration Coverage -arch x86_64 ONLY_ACTIVE_ARCH=NO

after_success:
  - ./coveralls.rb --extension m --exclude-folder Demo --exclude-folder Test --exclude-folder Externals
